model:
  base_learning_rate: 2.0e-06
  target: rec_network.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.02
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: augmented_image
    image_size: 32
    channels: 4
    concat_mode: true
    cond_stage_trainable: false
    conditioning_key: concat
    monitor: val/loss_simple_ema
    unet_config:
      target: rec_network.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8
        out_channels: 4
        model_channels: 256
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32

    first_stage_config:
      target: rec_network.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "./VAE/bottle.ckpt" #TODO: modify the ckpt_path of VAE
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 0
    wrap: false
    train:
      target: rec_network.data.mvtec.MVTecDRAEMTrainDataset
      params:
        root_dir: './datasets/mvtec/bottle/train/good' #TODO: modify the path of training samples
        anomaly_source_path: './datasets/dtd/images'
        resize_shape:
        - 256
        - 256


lightning:
  callbacks:
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True






